name: sbp
description: A new flutter plugin project.
version: 0.0.1

environment:
  sdk: ">=2.16.1 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.example.sbp
        pluginClass: SbpPlugin
      ios:
        pluginClass: SbpPlugin
